version: '3'
services:
  elk:
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/elk
    container_name: elk
    restart: "always"
    ports:
      - "45601:5601"
      - "49200:9200"
      - "45044:5044"
      - "49300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ../config/elk/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - ../data/elasticsearch_data/data:/var/lib/elasticsearch
      - ../data/elasticsearch_data/plugins:/opt/elasticsearch/plugins
      - ../log/elk/elasticsearch:/var/log/elasticsearch
      - ../log/elk/logstash:/var/log/logstash
      - ../data/logstash/patterns:/opt/logstash/patterns
      - ../config/elk/logstash/conf:/etc/logstash/conf.d
      - ../config/elk/kibana/kibana.yml:/opt/kibana/config/kibana.yml
    networks:
      - mogu

  filebeat:
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/filebeat
    container_name: filebeat
    restart: always
    networks:
      - mogu
    volumes:
     - ../config/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
     - ../log/elk/filebeat/:/opt/
     
networks:
  mogu:
    external: true
