version: '3.1'
services:
  nacos:
    image: registry.cn-shenzhen.aliyuncs.com/mogublog/nacos-server
    container_name: nacos_mogu
    env_file:
      - ./nacos/nacos-config.env
    volumes:
      - ../log/nacos/:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "41848:8848"
      - "49555:9555"
    restart: always
    networks:
      - mogu
      
networks:
  mogu:
    external: true
